[phases.setup]
providers = ["nodejs", "php"]
nodejs = "20"
php = "8.2"

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --port=${PORT:-8000} --host=0.0.0.0"