[phases.setup]
nixPkgs = ["php82", "nodejs-20_x", "npm"]

[phases.install]
cmds = ["composer install --no-dev", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --port=$PORT --host=0.0.0.0"